# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adam Hartz
email: ahartz1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A recent graduate of the Python Engineering course at The Iron Yard in Durham,&nbsp;NC, I am looking for a position as a Junior Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ahartz1.github.io" # the base hostname & protocol for your site
twitter_username: awareofnow
github_username:  ahartz1

# Build settings
markdown: kramdown
